
                type: object
                properties:
                  current_page:
                    type: integer
                  from:
                    type: integer
                  last_page:
                    type: integer
                  links:
                    type: array
                    items:
                      type: object
                      properties:
                        url:
                          type: string
                        label:
                          type: string
                        active:
                          type: boolean
                  path:
                    type: string
                  per_page:
                    type: integer
                  to:
                    type: integer
                  total:
                    type: integer
