openapi: 3.0.0
info:
  description: Documentação da api
  title: Mateus Desafio Laravel - Docs
  version: 0.0.4

servers:
  - url: /api

components:
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: Sanctum

paths:
  /auth/register:
    $ref: "./routes/auth/register/actions.yaml"
  /auth/login:
    $ref: "./routes/auth/login/actions.yaml"
  /auth/me:
    $ref: "./routes/auth/me/actions.yaml"
